packadd! dracula
syntax enable
colorscheme dracula
set nowrap
set number
set relativenumber
set tabstop=8 
set softtabstop=0 expandtab 
set shiftwidth=4 
set smarttab
set autoindent
set smartindent
set scrolloff=8
syntax on
